allow_entities_without_labels: true
index: false
testmode: false
batch: true
safe_label: loose
batch_size: 100000000
relation_type_threshold: 0.95
represent_values_and_annotations_as_json:
  iris:
    - http://purl.obolibrary.org/obo/IAO_0000115
    - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym

neo_node_labelling:
  - classes:
      - CL:0000548
    label: Animal_cell
    description: a cell that was sampled from an animal
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000996
    label: vagina
    description: a cell type that is associated with a vagina
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001690
    label: ear
    description: a cell type that is associated with an ear
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0005160
    label: vestigial_structure
    description: a cell type that is associated with a vestigial structure
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000160
    label: intestine
    description: a cell type that is associated with an intestine
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000970
    label: eye
    description: a cell type that is associated with an eye
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001705
    label: nail
    description: a cell type that is associated with a nail
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001021
    label: nerve
    description: a cell type that is associated with a nerve
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000992
    label: ovary
    description: a cell type that is associated with an ovary
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0003126
    label: trachea
    description: a cell type that is associated with a trachea
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001052
    label: rectum
    description: a cell type that is associated with a rectum
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001132
    label: parathyroid_gland
    description: a cell type that is associated with a parathyroid gland
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002046
    label: thyroid_gland
    description: a cell type that is associated with a thyroid 
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000007
    label: pituitary_gland
    description: a cell type that is associated with a pituitary gland
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001043
    label: esophagus
    description: a cell type that is associated with an oesophagus
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001300
    label: scrotum
    description: a cell type that is associated with a scrotum
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000056
    label: ureter
    description: a cell type that is associated with a ureter
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:3011048
    label: genital_system
    description: a cell type that is associated with a genital system
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001638
    label: vein
    description: a cell type that is associated with a vein
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0003889
    label: fallopian_tube
    description: a cell type that is associated with a fallopian tube
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001134
    label: skeletal_muscle_tissue
    description: a cell type that is associated with skeletal muscle tissue
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000989
    label: penis
    description: a cell type that is associated with a penis
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002369
    label: adrenal_gland
    description: a cell type that is associated with an adrenal gland
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001981
    label: blood_vessel
    description: a cell type that is associated with a blood vessel
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002073
    label: hair_follicle
    description: a cell type that is associated with a hair follicle
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001245
    label: anus
    description: a cell type that is associated with an anus
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002366
    label: bulbo-urethral_gland
    description: a cell type that is associated with a bulbourethral gland
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000955
    label: brain
    description: a cell type that is associated with a brain
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001905
    label: pineal_body
    description: a cell type that is associated with a pineal body
  - classes:
      - CL:0000000 and BFO:0000050 some CL:0000010
    label: cultured_cell
    description: a cell type that is associated with a cultured cell
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002106
    label: spleen
    description: a cell type that is associated with a spleen
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000310
    label: breast
    description: a cell type that is associated with a breast
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001264
    label: pancreas
    description: a cell type that is associated with a pancreas
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002095
    label: mesentery
    description: a cell type that is associated with a mesentary
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001154
    label: vermiform_appendix
    description: a cell type that is associated with a vermiform appendix
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0006562
    label: pharynx
    description: a cell type that is associated with a pharynx
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0012168
    label: umbilical_cord_blood
    description: a cell type that is associated with umbilical cord blood
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001898
    label: hypothalamus
    description: a cell type that is associated with a hypothalamus
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002048
    label: lung
    description: a cell type that is associated with a lung
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001723
    label: tongue
    description: a cell type that is associated with a tongue
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001982
    label: capillary
    description: a cell type that is associated with a capillary
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002110
    label: gall_bladder
    description: a cell type that is associated with a gallbladder
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000004
    label: nose
    description: a cell type that is associated with a nose
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002372
    label: tonsil
    description: a cell type that is associated with a tonsil
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0003672
    label: dentition
    description: a cell type that is associated with dentition
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002465
    label: lymphoid_system
    description: a cell type that is associated with a lymphoid system
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001987
    label: placenta
    description: a cell type that is associated with a placenta
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0018707
    label: bladder_organ
    description: a cell type that is associated with a bladder
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002097
    label: skin_of_body
    description: a cell type that is associated with the dermis or epidermis
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002113
    label: kidney
    description: a cell type that is associated with a kidney
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002411
    label: clitoris
    description: a cell type that is associated with a clitoris
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000002
    label: uterine_cervix
    description: a cell type that is associated with a uterine cervix
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001474
    label: bone_element
    description: a cell type that is associated with a bone
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000178
    label: blood
    description: a cell type that is associated with blood
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001044
    label: saliva-secreting_gland
    description: a cell type that is associated with a saliva-secreting gland
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000948
    label: heart
    description: a cell type that is associated with a heart
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0015143
    label: mesenteric_fat_pad
    description: a cell type that is associated with a mesenteric fat pad
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000165
    label: mouth
    description: a cell type that is associated with an oral cavity
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001637
    label: artery
    description: a cell type that is associated with an artery
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000473
    label: testis
    description: a cell type that is associated with a testis
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0005169
    label: interstitial_tissue
    description: a cell type that is associated with interstitial tissue
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001013
    label: adipose_tissue
    description: a cell type that is associated with adipose tissue
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001103
    label: diaphragm
    description: a cell type that is associated with a diaphragm
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000982
    label: skeletal_joint
    description: a cell type that is associated with a skeletal joint
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000043
    label: tendon
    description: a cell type that is associated with a tendon
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001737
    label: larynx
    description: a cell type that is associated with a larynx
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000995
    label: uterus
    description: a cell type that is associated with a uterus
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0008846
    label: skeletal_ligament
    description: a cell type that is associated with a skeletal ligament
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002240
    label: spinal_cord
    description: a cell type that is associated with a spinal cord
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001000
    label: vas_deferens
    description: a cell type that is associated with a vas deferens
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002108
    label: small_intestine
    description: a cell type that is associated with a small intestine
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002370
    label: thymus
    description: a cell type that is associated with a thymus
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002367
    label: prostate_gland
    description: a cell type that is associated with a thymus
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000997
    label: mammalian_vulva
    description: a cell type that is associated with a vulva
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0001911
    label: mammary_gland
    description: a cell type that is associated with a mammary gland
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000945
    label: stomach
    description: a cell type that is associated with a stomach
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000059
    label: large_intestine
    description: a cell type that is associated with a large intestine
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0002107
    label: liver
    description: a cell type that is associated with a liver
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000998
    label: seminal_vesicle
    description: a cell type that is associated with a seminal vesicle
  - classes:
      - CL:0000000 and BFO:0000050 some UBERON:0000057
    label: urethra
    description: a cell type that is associated with a urethra
  - classes:
      - UBERON:0010000
      - UBERON:0000178
    label: Multicellular_anatomical_structure
    description: an anatomical structure that has more than one cell as a part, including blood 
  - classes:
      - NCBITaxon:33208
    label: Metazoan  
    description: an organism that belongs to the division Metazoa or a term that is applicable to Metazoa
  - classes:
      - NCBITaxon:40674
    label: Mammalia
    description: an organism that belongs to the class Mammalia or a term that is applicable to Mammalia
  - classes:
      - NCBITaxon:7215
    label: Drosophila
    description: an organism that belongs to the genus Drosophila or a term that is applicable to Drosophila
  - classes:
      - NCBITaxon:8353
    label: Xenopus
    description: an organism that belongs to the genus Xenopus or a term that is applicable to Xenopus
  - classes:
      - NCBITaxon:6239
    label: Caenorhabditis_elegans
    description: an organism that belongs to the species C. elegans or a term that is applicable to C. elegans
  - classes:
      - NCBITaxon:7227
    label: Drosophila_melanogaster
    description: an organism that belongs to the species D. melanogaster or a term that is applicable to D. melanogaster
  - classes:
      - NCBITaxon:7955
    label: Danio_rerio
    description: an organism that belongs to the species D. rerio or a term that is applicable to D. rerio
  - classes:
      - NCBITaxon:9606
    label: Homo_sapiens
    description: an organism that belongs to the species H. sapiens or a term that is applicable to H. sapiens
  - classes:
      - HANCESTRO:0004
    label: Race
    description: a term that refers to the ancestry of a Homo sapiens
  - classes:
      - MONDO:0000001
    label: Disease
    description: a disease or disorder, plus 'normal' (latter pulled from SPARQL query)
  - classes:
      - UBERON:0000105
      - FBdv:00007012
      - WBls:0000075
      - ZFS:0100000
      - MmusDv:0000000
      - HsapDv:0000000
      - XAO:1000000
    label: Developmental_stage
    description: a term that refers to a life cycle stage

curie_map:
  GITHUB: https://github.com/
  GITHUBH: http://github.com/
  PMID: http://www.ncbi.nlm.nih.gov/pubmed/
  orcid: https://orcid.org/
  doi: https://doi.org/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ncbigene: http://www.ncbi.nlm.nih.gov/gene/
  cc: http://creativecommons.org/ns#
  pato_rel: http://purl.obolibrary.org/obo/pato#
  so_rel: http://purl.obolibrary.org/obo/so#
  ro_rel: http://www.obofoundry.org/ro/ro.owl#
  owl: http://www.w3.org/2002/07/owl#
  skos: http://www.w3.org/2004/02/skos/core#
  ensembl: http://identifiers.org/ensembl/
  RO: http://purl.obolibrary.org/obo/RO_
  UBERON: http://purl.obolibrary.org/obo/UBERON_
  CL: http://purl.obolibrary.org/obo/CL_
  n2o: http://n2o.neo/custom/
  ILX: http://uri.interlex.org/base/ilx_
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  PR: http://purl.obolibrary.org/obo/PR_
  SO: http://purl.obolibrary.org/obo/SO_
  OBI: http://purl.obolibrary.org/obo/OBI_
  PCL: http://purl.obolibrary.org/obo/PCL_
  HANCESTRO: http://purl.obolibrary.org/obo/HANCESTRO_
  MONDO: http://purl.obolibrary.org/obo/MONDO_
  EFO: http://www.ebi.ac.uk/efo/EFO_
  PATO: http://purl.obolibrary.org/obo/PATO_

filters:
  solr:
    exclusion:
      iri_prefix:
        - http://virtualflybrain.org/reports/VFBc_
      neo4j_node_label:
        - Channel
