
name: YAML schema validator
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'config/prod/neo4j2owl-config.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yaml-schema-validation:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install Yamale
      run: brew install yamale
    - name: schema validation
      run: yamale -s schema.yaml config/prod/neo4j2owl-config.yaml | tee validation.report
    - name: Prepare schema validator comment
      if: ${{ failure() }}
      run: "echo \"<details>\n <summary> config/prod/neo4j2owl-config.yaml file failed the schema validation check </summary> \n\" > comment.md; cat validation.report >> comment.md"
    - name: Post comment validator comment
      if: ${{ failure() }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      uses: NejcZdovc/comment-pr@v1.1.1
      with:
        file: "../../comment.md"
