name: YAML schema validator
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'config/prod/neo4j2owl-config.yaml'

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nrkno/yaml-schema-validator-github-action@v4
      with:
        schema: schema.yaml
        target: config/prod/neo4j2owl-config.yaml
        # Uncomment to disable strict checks
        # no-strict: true
